version: "3.8"

services:
  # vsftpd service
  ftp-server:
    image: fauria/vsftpd
    ports:
      - 21:21
      - 20:20
      - 21100-21110:21100-21110
    env_file:
      - .env.ftp
    restart: always

  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env.database

  object-storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /usr/minio/data:/data
    env_file:
      - .env.minio
  
  object-storage-config:
    image: minio/mc
    env_file: 
      - .env.minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio ${MINIO_HOST}  ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc admin user add obj_con ${MINIO_BANK_USER} ${MINIO_BANK_SECRET};
      "
    # #   - mc obj_con set minio ${MINIO_HOST} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
    # script: 
    #   - mc mb obj_con ${BANK_BUCKET_NAME}
    #   # - mc admin user add obj_con ${MINIO_BANK_USER} ${MINIO_BANK_SECRET}
    #   # - mc mb obj_con bank/dailyReports
    #   # - mc mb 
    depends_on:
      - object-storage
