version: '3.3'

# name: flask22

services:
  database:
    image: postgres
    ports:
      - 54323:5432
    restart: always
    env_file:
      - .env

  flask_service:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
